[package]
name = "rust-zserio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
antlr-rust = "0.3.0-beta"
bitreader = "0.3.6"
bitstream-io = "1.6.0"
codegen = "0.2.0"
convert_case = "0.6.0"
rstest = "0.16.0"
rust-bitwriter = { git = "https://github.com/Danaozhong/rust-bitwriter", version = "0.0.1" }
rust-format = "0.3.4"
walkdir = "2.3.2"
