[workspace]

members = [
    ".",
    "tests/reference-module-lib",
    "tests/round-trip-tests",
    "tests/compare-ref-impl-tests/rust",
]

[package]
name = "rust-zserio"
version = "0.0.0"
edition = "2021"
authors = ["Clemens Zangl <clemens.zangl@gmail.com>"]
exclude = [".pre-commit-config.yaml"]

description = """
Rust bindings for the zserio serialization protocol.
"""

documentation = "https://docs.rs/rust-zserio"
homepage = "https://github.com/Danaozhong/rust-zserio"
repository = "https://github.com/Danaozhong/rust-zserio"
license = "BSD-3-Clause"

[dependencies]
antlr-rust = "0.3.0-beta"
bitmask-enum = "2.2.4"
bitreader =  "0.3.8"
bitstream-io = "1.6.0"
clap = { version="4.2.7", features = [ "derive" ] }
codegen = "0.2.0"
convert_case = "0.6.0"
duplicate = "1.0.0"
half = "2.3.1"
itertools = "0.11.0"
num = "0.4.0"
proc-macro2 = "1.0.66"
rstest = "0.16.0"
rust-bitwriter = "0.0.1"
rustfmt-wrapper = "0.2.1"
thiserror = "1.0.61"
walkdir = "2.3.2"
