name: Release rust-zserio crate

on:
  push:
    tags:
      - 'v*.*.*'

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set version number
        run: |
          export VERSION=${{ github.ref_name }}
          sed -i "s/0.0.0/${VERSION:1}/g" Cargo.toml

      - name: Publish zserio
        run: cargo publish --allow-dirty -p zserio
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Publish zserio-rs-build
        run: cargo publish --allow-dirty -p zserio-rs-build
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Publish zserio
        run: cargo publish --allow-dirty -p rust-zserio
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
