name: Release packages

on:
  push:
    tags:
      - 'v*.*.*'

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install cargo-release
        run: cargo install cargo-release

      - name: Determine version number
        id: version
        run: |
          version=${{ github.ref_name }}
          echo "VERSION=${version:1}" >> "$GITHUB_OUTPUT"

      - name: Update version in Cargo.toml
        run: |
          echo "::group::Update version"
          cargo release version --workspace --no-confirm -x ${{ steps.version.outputs.VERSION }}
          echo "::endgroup::"
          echo "::group::Configure git"
          git config user.name github-actions[bot]
          git config user.email github-actions@github.com
          echo "::endgroup::"
          echo "::group::Commit changes"
          cargo release commit --no-confirm -x
          echo "::endgroup::"

      - name: Publish packages
        run: cargo release --workspace --no-tag --no-push --no-confirm -x ${{ steps.version.outputs.VERSION }}
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
