name: PR Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run Build test
      run: cargo build --release --verbose --all --all-targets
  test-unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run Unit tests
      run: cargo test --all --verbose
  test-e2e:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run E2E tests
      run: cargo run -p round-trip-tests
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: rustfmt, clippy
    - name: Run lint check
      run: cargo clippy --all --all-targets -- -D warnings
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
      with:
        github-token: ${{ github.token }}
    - name: Run fmt check
      shell: nix develop --impure .# -c bash -e {0}
      run: |
        # The E2E test works by generating the rust interface files to read/write zserio.
        # Since these files are referenced in the E2E test code, if these files are missing,
        # the linter checker will not be able to find them, and throw an error.
        cargo run -p round-trip-tests
        cargo fmt --all -- --check
