name: PR Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test rust-zserio Build
      run: cargo build --release --verbose
    - name: Test round-trip-tests Build
      run: cargo build --release -p round-trip-tests --verbose
  test-unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run Unit tests
      run: cargo test --verbose
  test-e2e:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run E2E tests
      run: cargo run -p round-trip-tests
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run lint check
      run: cargo clippy
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run fmt check
      run: |
        # somehow fmt check only work after running e2e test
        # it looks like e2e test will generate some files which is missing for fmt
        cargo run -p round-trip-tests
        cargo fmt --check
